name: flashcoders
description: Flash Coders company's vision is to create technology that empowers people to live better lives and make the world a better place, while also being mindful of the potential negative impacts of technology and working to mitigate them, and to do so in a way that is equitable, inclusive, sustainable, future-proof, and aligned with the UN Sustainable Development Goals, and that leaves a positive legacy for future generations.

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  #sdk
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #c
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.13.2

  #e
  extended_image: ^8.2.0

  #f
  flutter_animate: ^4.3.0
  firebase_core: ^2.23.0
  firebase_cached_image: ^0.4.5
  flutter_animated_button: ^2.0.3
  flutter_riverpod: ^2.4.8
  flutter_widget_from_html: ^0.14.7
  firebase_auth: ^4.14.1
  firebase_storage: ^11.5.2
  firebase_analytics: ^10.7.1

  #g
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6

  #h
  html_viewer_elite: ^0.0.4

  #i
  image_picker: ^1.0.4

  quill_html_editor: ^2.2.6

  #r
  responsive_framework: ^1.1.1
  #u
  url_launcher: ^6.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/logo/flash_coders_bg.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
