name: flashcoders
description: Flash Coders company's vision is to create technology that empowers people to live better lives and make the world a better place, while also being mindful of the potential negative impacts of technology and working to mitigate them, and to do so in a way that is equitable, inclusive, sustainable, future-proof, and aligned with the UN Sustainable Development Goals, and that leaves a positive legacy for future generations.

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  #sdk
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  #c
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.15.4

  #e
  extended_image: ^8.2.0

  #f
  flutter_animate: ^4.5.0
  firebase_core: ^2.25.4
  firebase_cached_image: ^0.5.3
  flutter_animated_button: ^2.0.3
  flutter_riverpod: ^2.4.10
  flutter_widget_from_html: ^0.14.11
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.5
  firebase_analytics: ^10.8.5

  #g
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1

  #h
  html_viewer_elite: ^0.0.4

  #i
  image_picker: ^1.0.7
  
  #q
  quill_html_editor: ^2.2.7

  #r
  responsive_framework: ^1.1.1

  #s
  supabase_flutter: ^2.3.3
  
  #u
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/logo/flash_coders_bg.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
