import 'package:supabase_flutter/supabase_flutter.dart';

String anonKey =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZudmF4bXVvY3pybWJyeGZrdXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDUxMjM5NzQsImV4cCI6MjAyMDY5OTk3NH0.m1LBfBPjOke5vTdUjHfYgztRHsfQj_sVWoPGB1YY2qw";
final supabase = Supabase.instance.client;
