const howToContributePath = "/getting-started/how-to-contribute";
const howToContributeHtml = """
<h1><span style="font-family: Georgia, serif;">How to Contribute?</span></h1>
<p><span style="font-size: 18px; font-family: Georgia, serif;">Step by Step process</span></p>
<ol>
    <li style="font-family: Georgia, serif;">&nbsp;<span style="font-size: 18px;">Clone website repo from github -<br>&nbsp;&nbsp;</span><a data-fr-linked="true" href="https://github.com/ps6067966/flashcoders.git" style="color: rgb(255, 255, 255);"><span style="font-size: 18px;">https://github.com/ps6067966/flashcoders.git</span></a><br>&nbsp;</li>
    <li style="font-family: Georgia, serif; font-size: 18px;">Run&nbsp;<strong><em>flutter pub get&nbsp;</em></strong>to fetch project dependecies&nbsp;<br><br></li>
    <li style="font-family: Georgia, serif; font-size: 18px;"><span style="font-size: 18px;">&nbsp;Have close look at repo folder structure, try to understand existing code.&nbsp;</span></li>
</ol>
<p><span style="font-family: Georgia, serif; font-size: 18px;">We have used <a href="https://pub.dev/packages/go_router" style="color: rgb(255, 255, 255);">go_router</a> for handling routes and deep link, <a href="https://pub.dev/packages/flutter_riverpod" style="color: rgb(255, 255, 255);">flutter_riverpod</a> as state management, and <a href="https://codewithandrea.com/articles/flutter-project-structure/" style="color: rgb(255, 255, 255);">features first approach</a>. Please read about these things so we can write better code together.&nbsp;</span><span style="font-family: Georgia, serif;"><br></span><br><span style="font-family: Georgia, serif;"><strong style="font-weight: 700; color: rgb(0, 0, 0); font-family: Georgia, serif; font-size: 24px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Project Roadmap</strong></span><br><span style="font-family: Georgia, serif;"><br></span><span style="font-family: Georgia, serif; font-size: 18px;">Checkout Roadmap V1, we have created a roadmap for this year.&nbsp;</span><span style="font-family: Georgia, serif;"><br></span><span style="font-family: Georgia, serif; font-size: 18px;">Link: <a data-fr-linked="true" href="https://github.com/users/ps6067966/projects/1" style="color: rgb(255, 255, 255);">https://github.com/users/ps6067966/projects/1</a></span></p>
<p><span style="font-family: Georgia, serif;"><br></span><span style="font-size: 24px; font-family: Georgia, serif;"><strong>Resources</strong></span></p>
<p><span style="font-size: 18px; font-family: Georgia, serif;">- Read about Notifier Provider here : <a data-fr-linked="true" href="https://docs-v2.riverpod.dev/docs/providers/notifier_provider" style="color: rgb(255, 255, 255);">https://docs-v2.riverpod.dev/docs/providers/notifier_provider</a></span><br><br><span style="font-size: 18px; font-family: Georgia, serif;">This is the most recommended approach of riverpod.&nbsp;</span><br><br><br><br></p>
<p><span style="font-family: Georgia, serif;"><br><br><br></span><br></p>
""";
